In [1]:
import numpy as np

In [2]:
x = np.arange(1, 7).reshape(2, 3)

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
x.flat[3]

4

In [5]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
x.T.flat[3]

5

In [7]:
type(x.flat)

numpy.flatiter

In [8]:
x.flat = 3; x

array([[3, 3, 3],
       [3, 3, 3]])

In [9]:
x.flat[[1,4]] = 1; x

array([[3, 1, 3],
       [3, 1, 3]])